# This CI will run after publish a new release

name: Publish Docker image
# https://docs.github.com/en/actions/publishing-packages/publishing-docker-images
# https://github.com/docker/metadata-action#semver
on:
  push:
    branches:
      - 'master'
    tags:
      - 'v*'
  pull_request:
    branches:
      - 'maaster'
# release:
#   types: [published]

env:
  REGISTRY: docker.io
# IMAGE_NAME: ${{ github.repository }}
  IMAGE_NAME: codebird/essl-docs
  IMAGE_TAG: 4.0.7

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out ESSL-Lab-Docs repo with sub-modules
        uses: actions/checkout@v2
      - name: Checkout submodules
        run: git submodule update --init --recursive
#       uses: textbook/git-checkout-submodule-action@master
#       with:
#         remote: true
#       with:
#         submodules: recursive

      - name: Generate Docker metadata
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
#           docker.io/${{ github.repository }}
#           ghcr.io/${{ github.repository }}
#           quay.io/${{ github.repository }}
          tags: type=semver,pattern={{major}}.{{minor}}.{{patch}},value=${{ env.IMAGE_TAG }}
#           type=semver,pattern={{major}}.{{minor}},value=${{ env.IMAGE_TAG }}
#           type=semver,pattern={{major}},value=${{ env.IMAGE_TAG }}
#         flavor: |
#           latest=true
      
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      
      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
