# This CI will run after publish a new release
#   https://github.com/marketplace/actions/docker-build-then-push

name: Continous Integration and Continous Delivery

on: [push]
# release:
#   types: [published]
  
jobs:
  processing_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
#     - name: Build and Test
#       # Run your CI script before build docker image  
#       run: make install && \
#            make test && \
#            make coverage && \
#            make cleanup
      - name: Starting pipeline
        run: echo Pipeline started!
    
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: codeird/ess-docs
          tags: v3, latest
          registry: docker.io
          dockerfile: Dockerfile.ci
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.PASSWORD }}