# This CI will run after publish a new release
#   https://github.com/marketplace/actions/docker-build-then-push

name: Continous Integration and Continous Delivery

on: [push]
# release:
#   types: [published]
  
jobs:
  processing_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
#     - name: Build and Test
#       # Run your CI script before build docker image  
#       run: make install && \
#            make test && \
#            make coverage && \
#            make cleanup
      - name: Starting pipeline
        run: echo Pipeline started!

      - name: Docker build then push
        uses: xCodeOwl/essl-lab-docs@master
        env:
            DOCKER_USER: ${{ secrets.DOCKER_USER }}
            PASSWORD: ${{ secrets.PASSWORD }}

            SEMVER: 0.1.0
            HOST: docker.com
            ORG: codebird
            APPNAME: essl-docs
            # if DEV is true then your image tag is as follow
            # 0.1.0-dev-c7bf9e21
            # where c7bf9e21 is your 8 char git hash
            # best for your staging server
            # else, the tag will be 0.1.0 ($SEMVER)
            DEV: false