# This CI will run after publish a new release

name: Continous Integration and Continous Delivery
#   https://github.com/marketplace/actions/docker-build-then-push

on: [push]
# release:
#   types: [published]
  
jobs:
  processing_docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        name: Check out code
#     - name: Build and Test
#       # Run your CI script before build docker image  
#       run: make install && \
#            make test && \
#            make coverage && \
#            make cleanup
      - name: Starting pipeline
        run: echo Pipeline started!
    
      - uses: mr-smithers-excellent/docker-build-push@v5
        name: Build & push Docker image
        with:
          image: codebird/essl-docs
          tags: v3, latest
#         registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
